# Generated by Django 6.0.6 on 2026-07-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_login_identifier_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
