# Generated by Django 5.2.4 on 2026-06-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_student_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='class_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
