# Generated by Django 5.2.4 on 2026-06-12 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_student_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='identifier',
        ),
    ]
