# Generated by Django 5.2.4 on 2026-06-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_alter_teacher_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone',
        ),
    ]
