# Generated by Django 5.2.4 on 2026-06-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_teacher_first_name_remove_teacher_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
