# Generated by Django 5.2.4 on 2026-06-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_student_first_name_remove_student_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='academic_session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='created_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='section',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
