# Generated by Django 5.2.4 on 2026-06-15 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.classroom'),
        ),
    ]
