# Generated by Django 5.2.4 on 2026-06-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_classroom_class_teacher_teacher_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classroom',
        ),
        migrations.AddField(
            model_name='teacher',
            name='classroom',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='academics.classroom'),
        ),
    ]
