# Generated by Django 5.2.4 on 2026-06-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_remove_teacher_classroom_teacher_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='designation',
            field=models.CharField(blank=True, null=True),
        ),
    ]
