# Generated by Django 5.2.4 on 2026-06-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_student_address_student_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
