# Generated by Django 5.2.4 on 2026-06-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_student_emergency_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='class_id',
        ),
    ]
