# Generated by Django 5.2.4 on 2026-06-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_designation_employee_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(null=True),
        ),
    ]
