# Generated by Django 5.2.4 on 2026-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, null=True),
        ),
    ]
