# Generated by Django 5.2.4 on 2026-06-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='classroom',
            field=models.ManyToManyField(blank=True, null=True, related_name='employee', to='academics.classroom'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
