# Generated by Django 5.2.4 on 2026-06-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_employee_classroom_alter_employee_emp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
    ]
