# Generated by Django 5.2.4 on 2026-06-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='created_at',
        ),
    ]
