# Generated by Django 5.2.4 on 2026-06-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_remove_classroom_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(blank=True, null=True),
        ),
    ]
