# Generated by Django 5.2.4 on 2026-06-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_alter_student_emergency_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
