# Generated by Django 5.2.4 on 2026-06-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0030_alter_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, null=True),
        ),
    ]
