# Generated by Django 5.2.4 on 2026-06-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0031_student_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='academic_session',
        ),
    ]
