# Generated by Django 5.2.4 on 2026-06-25 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0032_remove_classroom_academic_session'),
        ('accounts', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
    ]
