# Generated by Django 6.0.6 on 2026-06-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0035_department'),
        ('accounts', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
    ]
