# Generated by Django 6.0.6 on 2026-06-30 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0036_alter_department_organization'),
        ('accounts', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='accounts.organization'),
        ),
    ]
