# Generated by Django 6.0.6 on 2026-06-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0037_department_department_alter_department_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='department_name',
        ),
    ]
