# Generated by Django 6.0.6 on 2026-07-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0040_student_updated_at'),
        ('accounts', '0006_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='academics.classroom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='accounts.organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='academics.subject')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('classroom', 'subject'), name='unique_classroom_subject')],
            },
        ),
    ]
