# Generated by Django 6.0.6 on 2026-07-02 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0041_subject_classroomsubject'),
        ('accounts', '0006_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='organization',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='accounts.organization'),
        ),
    ]
