# Generated by Django 6.0.6 on 2026-07-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0042_subject_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'designation': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_subjects', to='academics.employee'),
        ),
    ]
