# Generated by Django 6.0.6 on 2026-07-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0044_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
    ]
