# Generated by Django 6.0.6 on 2026-07-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0047_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='section',
        ),
    ]
