# Generated by Django 6.0.6 on 2026-07-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0049_section'),
        ('accounts', '0006_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='organization',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
            preserve_default=False,
        ),
    ]
