# Generated by Django 6.0.6 on 2026-07-16 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0050_section_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='academics.employee'),
            preserve_default=False,
        ),
    ]
