# Generated by Django 6.0.6 on 2026-07-16 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0051_alter_section_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='academics.section'),
            preserve_default=False,
        ),
    ]
