# Generated by Django 6.0.6 on 2026-07-17 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0052_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.employee'),
        ),
    ]
