# Generated by Django 6.0.6 on 2026-07-17 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0053_alter_section_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.classroom'),
        ),
    ]
