# Generated by Django 6.0.6 on 2026-07-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancesession',
            old_name='clasroom_subject',
            new_name='classroom_subject',
        ),
    ]
