# Generated by Django 6.0.6 on 2026-07-17 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_clasroom_subject_attendancesession_classroom_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='classroom_subject',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='teacher',
        ),
        migrations.RemoveConstraint(
            model_name='studentattendance',
            name='unique_student_attendance',
        ),
        migrations.RemoveConstraint(
            model_name='teacherattendance',
            name='unique_teacher_attendance',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='attendance_session',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherattendance',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='AttendanceSession',
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='TeacherAttendance',
        ),
    ]
