# Generated by Django 6.0.6 on 2026-07-17 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0053_alter_section_class_teacher'),
        ('attendance', '0003_remove_attendancesession_classroom_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeFaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faces/')),
                ('embedding', models.JSONField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='faces/')),
                ('embedding', models.JSONField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.student')),
            ],
        ),
    ]
