# Generated by Django 6.0.6 on 2026-07-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfaceprofile',
            old_name='employee',
            new_name='student',
        ),
    ]
